### ISSUE TITLE
Documentation fixes for how to install DataPull in AWS, do documentation, fix dependency vulnetability

### ISSUE THREAD

**Issue by markovarghese** [homeaway/datapull#22]
**Is your feature request related to a problem? Please describe.**
There are some minor typos in the root readme.md. There are some formatting issues and the lack of diagrams in the documentation for how to install DataPull in AWS. There is also a dependency vulnerability reported by github.

**Describe the solution you'd like**
Need to fix the typos, fix formatting issues and add diagrams if time permits. Also fix dependency vulnerability

**Describe alternatives you've considered**
Considered making this 2 issues instead of one; but decided against it since this stuff is really minor.

**Additional context**
N/A

**Comment by srinugajjala** [comment]
https://github.com/homeaway/datapull/pull/23
https://github.com/homeaway/datapull/pull/24
