### ISSUE TITLE
Elasticsearch examples use docs as _type, which is non-default and deprecated

### ISSUE THREAD

**Issue by markovarghese** [homeaway/datapull#81]
**Describe the bug**
Ref https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html ; users tend to copy the examples when using the platform objects for the input json. For elasticsearch, the "type" attribute is set to "docs", which shows up on the index as "_type". This doesn't break DataPull per se, but it breaks apps who use the indexes written by datapull. Those apps sometimes filter on the type with default value "_doc". 

**Expected behavior**
* The ES examples should use the type as "_doc". 
* The "type" attribute should optional. If the type is not specified, for ES versions where the type is deprecated, it should not be set at all; else it should be set to the default value "_doc"

**Comment by niravns** [comment]
I think this is not a bug as the elastic search team accepted that they made a bad analogy of equating mapping types and with table, so I think its more of planned obsolescence on ES resulting in the issue.Thus updated the label from bug to deprecation.
